title: Evo Automotive Solutions

theme: jekyll-bulma-feather

author: 'Ryan S. Northrup ("RyNo")'
navbar:
  title: Evo Automotive Solutions
  logo: /assets/evo-logo-500-rv.png
  start:
    - title: Products
      url: /#products
    - title: About us
      url: /#aboutus
    - title: Contact us
      url: /#contactus
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
